FROM openjdk:16-slim
MAINTAINER chloelovesdev <chloelovesdev@gmail.com>

COPY java_lookup_main.sh /usr/local/bin/java_lookup_main.sh
RUN chmod +x /usr/local/bin/java_lookup_main.sh

RUN useradd -m -d /sandbox sandbox